routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::prefix('/auth')->group(function () {
    Auth::routes();
});

Route::get('/@{user}', 'ProfileController@show')->name('profile.show');
Route::get('/@{user}/edit', 'ProfileController@edit')->name('profile.edit');

Route::get('/notifications', 'NotificationController@index')->name('notifications');

Route::prefix('/conversations')->namespace('Conversations')->name('conversation.')->middleware('auth')->group(function () {
    Route::get('/', 'ConversationController@index')->name('index');
    Route::get('/list', 'ConversationController@get_conversations')->name('list');
    Route::get('/new', 'ConversationController@new')->name('new');
    Route::get('/{user}/messages', 'ConversationController@messages')->name('messages');
    Route::post('/{user}/send', 'ConversationController@send')->name('send');
});

Route::prefix('/settings')
        ->name('settings.')
        ->middleware(['auth'])
        ->namespace('Settings')
        ->group(function () {

    Route::get('/', function () {
        return redirect()->route('settings.profile');
    });

    Route::get('/profile', 'ProfileSettingsController@edit')->name('profile'); // profile picture, biography, website ...
    Route::patch('/profile', 'ProfileSettingsController@update')->name('profile.update'); // save

    Route::get('/password', 'PasswordSettingsController@edit')->name('password');
    Route::patch('/password', 'PasswordSettingsController@update')->name('password.update');

    // Route::get('/account', 'SettingsController@index')->name('profile'); // username, deactivate account
    // Route::get('/privacy', 'SettingsController@privacy')->name('settings.privacy');
    // Route::get('/notifications', 'SettingsController@notifications')->name('settings.notifications');
    // Route::resource('/deactivate', 'SettingsController')->only(['index', 'delete']);

});

Route::prefix('/discussions')->namespace('Discussions')->group(function () {
    Route::get('/{category?}', 'DiscussionController@index')->name('discussion.index'); // category is optional
    Route::get('/{category}/create', 'DiscussionController@create')->name('discussion.create');
    Route::post('/{category}', 'DiscussionController@store')->name('discussion.store');
    Route::get('/{category}/{discussion}', 'DiscussionController@show')->name('discussion.show');
    Route::get('/{category}/{discussion}/edit', 'DiscussionController@edit')->name('discussion.edit');
    Route::patch('/{category}/{discussion}', 'DiscussionController@update')->name('discussion.update');
    Route::delete('/{category}/{discussion}', 'DiscussionController@destroy')->name('discussion.delete');

    Route::post('/{category}/{discussion}/likes', 'DiscussionLikeController@store')->name('discussion.like.store');
    Route::delete('/{category}/{discussion}/likes', 'DiscussionLikeController@destroy')->name('discussion.like.destroy');

    Route::post('/{category}/{discussion}/lock', 'DiscussionLockController@store')->name('discussion.lock.store');
    Route::delete('/{category}/{discussion}/lock', 'DiscussionLockController@destroy')->name('discussion.lock.destroy');

    Route::post('/{category}/{discussion}/pin', 'DiscussionPinController@store')->name('discussion.pin.store');
    Route::delete('/{category}/{discussion}/pin', 'DiscussionPinController@destroy')->name('discussion.pin.destroy');

    Route::get('/search', 'DiscussionSearchController@search')->name('discussion.search');

    Route::prefix('/{category}/{discussion}/replies')->namespace('Replies')->group(function () {
        Route::post('/{reply?}', 'DiscussionReplyController@store')->name('discussion.reply.store');
        Route::post('/{reply}/likes', 'DiscussionReplyLikeController@store')->name('discussion.reply.like.store');
        Route::delete('/{reply}/likes', 'DiscussionReplyLikeController@delete')->name('discussion.reply.like.delete');

        Route::post('/{reply}/best', 'DiscussionBestReplyController@store')->name('discussion.reply.best.store');
    });
});

// admin :
Route::prefix('/admin')->name('admin.')->namespace('Admin')->middleware(['auth', 'role:admin'])->group(function () {

    Route::get('/', 'AdminController@index')->name('index');

    Route::resource('users', 'UserController'); // names van 'resource' routes worden automatisch gegenereerd

    Route::get('/invite-users', 'UserInviteController@form')->name('invite-users');
    Route::post('/invite-users', 'UserInviteController@send_invites')->name('invite-users.send');

    Route::resource('projects', 'ProjectController');

    Route::resource('categories', 'CategoryController');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Traits\HasPermissions;

class User extends Authenticatable {
    use Notifiable;
    use HasRoles;

    private $_gitea_client = null;
    private $_gitea_user   = null;

    public function getRouteKeyName()
    {
        return 'username';
    }

    /**
     * Messages directed to this user
     */
    public function inbox_messages()
    {
        return $this->hasMany('App\Message', 'destination_user_id')->orderBy('created_at', 'DESC');
    }

    /**
     * Messages sent by this user
     */
    public function outbox_messages()
    {
        return $this->hasMany('App\Message', 'source_user_id');
    }

    public function avatar()
    {
        return 'https://www.gravatar.com/avatar/' . md5(strtolower(trim(auth()->user()->email))) . '?d=mp';
    }


    public function projects()
    {
        return $this->belongsToMany('App\Project', 'project_user');
    }

    public function get_git_url()
    {
        if ($this->gitea_id === null)
        {
            return 'no-associated-account';
        }

        return env('GITEA_URL') . '/' . $this->username;
        // return $this->_gitea_user;
    }

    /**
     * Retrieve public data as array
     */
    public function getPublicData()
    {
        return [
            'id' => $this->id,
            'username' => $this->username,
            'avatar' => $this->avatar(),
            'git_url' => $this->get_git_url()
        ];
    }

    public function discussions()
    {
        return $this->hasMany(Discussion::class);
    }


    /**
     * Items that the user has liked, NOT the likes received by this user
     */
    public function likes()
    {
        return $this->hasMany('App\Like');
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Hoeft denk ik niet?
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'username'=>'required',
            'email'=>'required'
        ]);

        $user = new User([
            'id' => $request->get('id'),
            'username' => $request->get('username'),
            'email' => $request->get('email')
        ]);
        $user->save();
        return redirect(route('admin.users.index'))->with('success', 'User saved.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        // $user = User::find($id);
        return view('admin.users.edit', compact('users', 'user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'username'=>'required',
            'email'=>'required'
        ]);

        $user->username = $request->get('username');
        $user->email = $request->get('email');
        $user->save();

        return redirect(route('admin.users.index'))->with(['status' => 'User updated.', 'type' => 'success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect(route('admin.users.index'))->with(['status' => 'User deleted.', 'type' => 'success']);
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3 text-xl mb-2">Update a user</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('admin.users.update', $user) }}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="first_name" class="w-32 inline-block">Name:</label>
                <input type="text" class="form-control mb-2 pl-1 border" name="username" value={{ $user->username }} >
            </div>
            <div class="form-group">
                <label for="email" class="w-32 inline-block">Email:</label>
                <input type="text" class="form-control mb-2 pl-1 border" name="email" value={{ $user->email }} >
            </div>
            <div class="form-group">
                <label for="city" class="w-32 inline-block">Password:</label>
                <input type="text" class="form-control mb-2 pl-1 border" name="password" value={{ $user->password }} >
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.index')

@section('tabmenu')

<a href="{{ route('admin.invite-users') }}" class="btn inline-block m-4 mb-0">Invite users</a>

<div class="row py-4 px-4">
    <div class="col-sm-12">
      <table class="table-auto">
        <thead>
            <tr>
              <th class="px-4 py-2">ID</th>
              <th class="px-4 py-2">Name</th>
              <th class="px-4 py-2">Email</th>
              <th class="px-4 py-2" colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
            <tr>
                <td class="border px-4 py-2">{{$user->id}}</td>
                <td class="border px-4 py-2">{{$user->username}}</td>
                <td class="border px-4 py-2">{{$user->email}}</td>
                <td class="border px-4 py-2">

                <a href="{{ route('admin.users.edit', $user)}}">
                <button class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15.2322 5.23223L18.7677 8.76777M16.7322 3.73223C17.7085 2.75592 19.2914 2.75592 20.2677 3.73223C21.244 4.70854 21.244 6.29146 20.2677 7.26777L6.5 21.0355H3V17.4644L16.7322 3.73223Z" stroke="#4A5568" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </button>
                </a>
                </td>
                <td class="border px-4 py-2">
                    <form action="{{ route('admin.users.destroy', $user)}}" method="post">
                      @csrf
                      @method('DELETE')
                      <button class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" type="submit">
                      <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M19 7L18.1327 19.1425C18.0579 20.1891 17.187 21 16.1378 21H7.86224C6.81296 21 5.94208 20.1891 5.86732 19.1425L5 7M10 11V17M14 11V17M15 7V4C15 3.44772 14.5523 3 14 3H10C9.44772 3 9 3.44772 9 4V7M4 7H20" stroke="#4A5568" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                      </svg></button>
                    </form>
                </td>
            </tr>
            @endforeach
        </tbody>
      </table>
    </div>
</div>

@endsection

resources/views/admin/users/invite.blade.php
@extends('layouts.app')

@section('content')


<h1 class="text-gray-700 tracking-wider mx-1">
    Importeer
</h1>

<div class="relative mb-8">
    <div class="bg-white rounded-t-lg border border-gray-400 p-4 mt-4 max-w-2xl">

        @isset($message)
        <p class="mb-4">{{ $message }}</p>
        @endisset

        @if(!is_null(session('amount_success')) && session('amount_success') > 0)
            <div class="bg-green-100 border-t-4 border-green-500 rounded-b text-green-900 px-4 py-3 shadow-md mb-6" role="alert">
                <div class="flex">
                    <div class="py-1"><svg class="fill-current h-6 w-6 text-green-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
                    <div>
                        <p class="font-bold">{{ session('amount_success') }} {{ Str::plural('email', session('amount_success')) }} have been sent.</p>
                    </div>
                </div>
            </div>
        @endisset

        @if(is_array(session('email_errors')) && !empty(session('email_errors')))
            <div class="bg-red-100 border-t-4 border-red-500 rounded-b text-red-900 px-4 py-3 shadow-md mb-6" role="alert">
                <div class="flex">
                    <div class="py-1"><svg class="fill-current h-6 w-6 text-red-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
                    <div>
                        <p class="font-bold">Not all emails have been sent successfully.</p>
                        @if(!is_null(session('amount_success')) && !is_null(session('amount_total') ))
                            <p class="text-sm">{{ session('amount_failed') }} of the {{ session('amount_total') }} ({{ sprintf("%01.2f", (session('amount_failed')/session('amount_total'))*100) }}%) of the e-mails have failed to send.</p>
                        @endif

                        @if(is_array(session('email_errors')))
                            <ul class="list-disc">
                            @foreach(session('email_errors') as $email_error)
                                <li class="text-red-500">{{ $email_error['email'] }}, {{ $email_error['error'] }}</li>
                            @endforeach
                            </ul>
                        @endif
                    </div>
                </div>
            </div>
        @endif

        <form class="w-full max-full" method="POST" action="{{ route('admin.invite-users.send') }}">
        @csrf

            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
                        The invite-links expire:
                    </label>
                    <label><input name="expiration_enabled" class="bg-gray-200 text-gray-700 border border-red-500 mb-3 focus:outline-none focus:bg-white" type="radio" value="1" {{ is_null(old('expiration_enabled')) || old('expiration_enabled') == '1'  ? 'checked' :'' }} > Yes</label>
                    <label><input name="expiration_enabled" class="bg-gray-200 text-gray-700 border border-red-500 mb-3 focus:outline-none focus:bg-white" type="radio" value="0" {{ old('expiration_enabled') == '0' ? 'checked' :'' }} > No</label>
                    @error('expiration_enabled')
                        <p class="text-red-600 text-xs italic">{{ $message }}</p>
                    @enderror
                </div>
                <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="grid-first-name">
                        Expiration date
                    </label>
                    <input name="expiration_date" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-grey-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="grid-first-name" type="date" placeholder="Jane" value="{{ old('expiration_date') }}">
                    @error('expiration_date')
                        <p class="text-red-600 text-xs italic">{{ $message }}</p>
                    @enderror
                </div>
            </div>
            <div class="flex flex-wrap -mx-3 mb-6">
                <div class="w-full px-3">
                    <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold" for="grid-password">
                        emailaddresses
                    </label>
                    <p class="text-gray-700 text-xs italic mb-3">one per line</p>
                    <textarea name="emailaddresses" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-500">{{old('emailaddresses')}}</textarea>
                    @error('emailaddresses')
                        <p class="text-red-600 text-xs italic">{{ $message }}</p>
                    @enderror
                    {{-- <p class="text-gray-600 text-xs italic">Make it as long and as crazy as you'd like</p> --}}
                </div>
            </div>
            <div class="flex flex-wrap flex-row-reverse -mx-3 mb-2">
                <div class="w-full md:w-1/3 mb-0 px-3">
                    <button type="submit" class="w-full btn btn-blue">
                    Send
                    </button>
                </div>
            </div>
        </form>
    </div>
</div>


@endsection


@if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
@endif