routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::prefix('/auth')->group(function () {
    Auth::routes();
});

Route::get('/@{user}', 'ProfileController@show')->name('profile.show');
Route::get('/@{user}/edit', 'ProfileController@edit')->name('profile.edit');

Route::get('/notifications', 'NotificationController@index')->name('notifications');

Route::prefix('/conversations')->namespace('Conversations')->name('conversation.')->middleware('auth')->group(function () {
    Route::get('/', 'ConversationController@index')->name('index');
    Route::get('/list', 'ConversationController@get_conversations')->name('list');
    Route::get('/new', 'ConversationController@new')->name('new');
    Route::get('/{user}/messages', 'ConversationController@messages')->name('messages');
    Route::post('/{user}/send', 'ConversationController@send')->name('send');
});

Route::prefix('/settings')
        ->name('settings.')
        ->middleware(['auth'])
        ->namespace('Settings')
        ->group(function () {

    Route::get('/', function () {
        return redirect()->route('settings.profile');
    });

    Route::get('/profile', 'ProfileSettingsController@edit')->name('profile'); // profile picture, biography, website ...
    Route::patch('/profile', 'ProfileSettingsController@update')->name('profile.update'); // save

    Route::get('/password', 'PasswordSettingsController@edit')->name('password');
    Route::patch('/password', 'PasswordSettingsController@update')->name('password.update');

    // Route::get('/account', 'SettingsController@index')->name('profile'); // username, deactivate account
    // Route::get('/privacy', 'SettingsController@privacy')->name('settings.privacy');
    // Route::get('/notifications', 'SettingsController@notifications')->name('settings.notifications');
    // Route::resource('/deactivate', 'SettingsController')->only(['index', 'delete']);

});

Route::prefix('/discussions')->namespace('Discussions')->group(function () {
    Route::get('/{category?}', 'DiscussionController@index')->name('discussion.index'); // category is optional
    Route::get('/{category}/create', 'DiscussionController@create')->name('discussion.create');
    Route::post('/{category}', 'DiscussionController@store')->name('discussion.store');
    Route::get('/{category}/{discussion}', 'DiscussionController@show')->name('discussion.show');
    Route::get('/{category}/{discussion}/edit', 'DiscussionController@edit')->name('discussion.edit');
    Route::patch('/{category}/{discussion}', 'DiscussionController@update')->name('discussion.update');
    Route::delete('/{category}/{discussion}', 'DiscussionController@destroy')->name('discussion.delete');

    Route::post('/{category}/{discussion}/likes', 'DiscussionLikeController@store')->name('discussion.like.store');
    Route::delete('/{category}/{discussion}/likes', 'DiscussionLikeController@destroy')->name('discussion.like.destroy');

    Route::post('/{category}/{discussion}/lock', 'DiscussionLockController@store')->name('discussion.lock.store');
    Route::delete('/{category}/{discussion}/lock', 'DiscussionLockController@destroy')->name('discussion.lock.destroy');

    Route::post('/{category}/{discussion}/pin', 'DiscussionPinController@store')->name('discussion.pin.store');
    Route::delete('/{category}/{discussion}/pin', 'DiscussionPinController@destroy')->name('discussion.pin.destroy');

    Route::get('/search', 'DiscussionSearchController@search')->name('discussion.search');

    Route::prefix('/{category}/{discussion}/replies')->namespace('Replies')->group(function () {
        Route::post('/{reply?}', 'DiscussionReplyController@store')->name('discussion.reply.store');
        Route::post('/{reply}/likes', 'DiscussionReplyLikeController@store')->name('discussion.reply.like.store');
        Route::delete('/{reply}/likes', 'DiscussionReplyLikeController@delete')->name('discussion.reply.like.delete');

        Route::post('/{reply}/best', 'DiscussionBestReplyController@store')->name('discussion.reply.best.store');
    });
});

// admin :
Route::prefix('/admin')->name('admin.')->namespace('Admin')->middleware(['auth', 'role:admin'])->group(function () {

    Route::get('/', 'AdminController@index')->name('index');

    Route::resource('users', 'UserController'); // names van 'resource' routes worden automatisch gegenereerd

    Route::get('/invite-users', 'UserInviteController@form')->name('invite-users');
    Route::post('/invite-users', 'UserInviteController@send_invites')->name('invite-users.send');

    Route::resource('projects', 'ProjectController');

    Route::resource('categories', 'CategoryController');

});

resources/views/layouts/app.blade.php
@extends ('layouts.boilerplate')

@section('app-notification')
@if (Session::get('status'))
    <app-notification
            message="{{ Session::get('status') }}"

            @if (Session::get('type'))
            type="{{ Session::get('type') }}"
            @endif

            @if (Session::get('duration'))
            duration="{{ Session::get('duration') }}"
            @endif
    ></app-notification>
@endif
@endsection

@section ('base')
    <div class="flex h-screen w-screen">
        <aside class="hidden lg:block w-full max-w-xs px-8 py-4 bg-white border-r border-gray-300">
            <div class="h-16 -mt-4 flex items-center">
                <a
                        href="/"
                        class="inline-block"
                >
                    <img
                        src="{{ asset('images/logo.svg') }}"
                        alt="Logo"
                        class="h-10"
                    >
                </a>
            </div>
            <nav class="mt-6">
                <div>
                    <h2 class="text-gray-500 text-sm font-bold tracking-wider uppercase">
                        Menu
                    </h2>
                    <div class="mt-4">
                        <a href="{{ route('home') }}" class="nav-link {{ Request::segment(1) === null ? 'active' :
                            null }}"
                        >
                            <div>
                                <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none">
                                    <path d="M3 12L5 10M5 10L12 3L19 10M5 10V20C5 20.5523 5.44772 21 6 21H9M19 10L21
                                    12M19 10V20C19 20.5523 18.5523 21 18 21H15M9 21C9.55228 21 10 20.5523 10 20V16C10
                                     15.4477 10.4477 15 11 15H13C13.5523 15 14 15.4477 14 16V20C14 20.5523 14.4477 21
                                      15 21M9 21H15" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                          stroke-linejoin="round"/>
                                </svg>
                            </div>
                            <span class="ml-3">
                                Home
                            </span>
                        </a>
                        <a href="{{ env('GITEA_URL') }}" target="_blank" class="nav-link mt-2 {{ (Request::segment(1) ===
                            'projects') ? 'active' : null }}"
                        >
                            <div>
                                <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none">
                                    <path
                                        d="M3 7V17C3 18.1046 3.89543 19 5 19H19C20.1046 19 21 18.1046 21 17V9C21 7.89543 20.1046 7 19 7H13L11 5H5C3.89543 5 3 5.89543 3 7Z"
                                        stroke="currentColor"
                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                            </div>
                            <span class="ml-3">
                                Projects
                            </span>
                        </a>
                        <a href="{{ route('discussion.index') }}" class="nav-link mt-2 {{ Request::segment(1) ===
                        'discussions' ? 'active' : null }}"
                        >
                            <div>
                                <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none">
                                    <path
                                        d="M8 12H8.01M12 12H12.01M16 12H16.01M21 12C21 16.4183 16.9706 20 12 20C10.4607 20 9.01172 19.6565 7.74467 19.0511L3 20L4.39499 16.28C3.51156 15.0423 3 13.5743 3 12C3 7.58172 7.02944 4 12 4C16.9706 4 21 7.58172 21 12Z"
                                        stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round"/>
                                </svg>
                            </div>
                            <span class="ml-3">
                                Discussions
                            </span>
                        </a>
@role('admin')
                        <div class="border-b border-gray-400 mt-3"></div>
                        <a href="{{ route('admin.users.index') }}" class="flex items-center -ml-4 -mr-4 px-4 py-2 mt-2 text-gray-500 rounded-md
                        hover:text-blue-700 hover:bg-blue-100">
                            <div>
                            </div>
                            <span class="font-medium ml-3">
                                Admin
                            </span>
                        </a>
@endrole
                    </div>
                    <div class="mt-6">
                        @yield ('sidebar')
                    </div>
                </div>
            </nav>
        </aside>
        <div class="flex-1 overflow-auto">
            <header class="bg-white h-16 w-full px-12 border-b border-gray-300">
                <div class="w-full h-full flex items-center justify-between">
                    <div class="relative flex-1">
                        <label for="search" class="absolute inset-y-0 text-gray-600 pl-4 flex items-center">
                            <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none">
                                <path
                                        d="M21 21L15 15M17 10C17 13.866 13.866 17 10 17C6.13401 17 3 13.866 3 10C3 6.13401 6.13401 3 10 3C13.866 3 17 6.13401 17 10Z"
                                        stroke="currentColor"
                                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                            </svg>
                        </label>
                        <input
                            type="text"
                            id="search"
                            name="search"
                            placeholder="Search"
                            class="input w-full max-w-sm pl-12"
                        >
                    </div>
                    <div class="ml-10 flex items-center">
                        <a href="{{ route('conversation.index') }}" class="mr-2 p-2 rounded-full text-gray-600 hover:text-blue-700 hover:bg-blue-100
                        focus:text-blue-700 focus:bg-blue-100 focus:outline-none focus:shadow-outline">
                            <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none">
                                <path
                                    d="M3 8L10.8906 13.2604C11.5624 13.7083 12.4376 13.7083 13.1094 13.2604L21 8M5 19H19C20.1046 19 21 18.1046 21 17V7C21 5.89543 20.1046 5 19 5H5C3.89543 5 3 5.89543 3 7V17C3 18.1046 3.89543 19 5 19Z"
                                    stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round"/>
                            </svg>
                        </a>
                        <a class="mr-6 p-2 rounded-full text-gray-600 hover:text-blue-700 hover:bg-blue-100
                        focus:text-blue-700 focus:bg-blue-100 focus:outline-none focus:shadow-outline">
                            <svg class="h-6 w-6" viewBox="0 0 24 24" fill="none">
                                <path
                                        d="M15 17H20L18.5951 15.5951C18.2141 15.2141 18 14.6973 18 14.1585V11C18 8.38757 16.3304 6.16509 14 5.34142V5C14 3.89543 13.1046 3 12 3C10.8954 3 10 3.89543 10 5V5.34142C7.66962 6.16509 6 8.38757 6 11V14.1585C6 14.6973 5.78595 15.2141 5.40493 15.5951L4 17H9M15 17V18C15 19.6569 13.6569 21 12 21C10.3431 21 9 19.6569 9 18V17M15 17H9"
                                        stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round"/>
                            </svg>
                        </a>
                        <app-profile-dropdown
                                username="{{ auth()->user()->username }}"
                                avatar-url="{{ auth()->user()->avatar() }}"
                                profile-url="/"
                        >
                            <div>

                            </div>
                            <a href="#" class="block px-2 py-2 hover:bg-gray-100">
                                My Profile
                            </a>
                            <a href="{{ route('settings.') }}" class="block px-2 py-2 hover:bg-gray-100">
                                Settings
                            </a>
                            <form action="{{ route('logout') }}" method="POST" class="w-full">
                                @csrf

                                <button type="submit" class="block w-full text-left px-2 py-2 hover:bg-gray-100">
                                    Log Out
                                </button>
                            </form>
                        </app-profile-dropdown>
                    </div>
                </div>
            </header>
            @if(View::hasSection('extra_content_aside'))
                @yield('extra_content_h1')
                <main class="px-8 flex">
                    @yield('extra_content_aside')
                    <div class="container px-5 pb-6 overflow-auto">
                        @yield ('app-notification')
                        @yield ('content')
                </div>
            </main>
@else
            <main class="mx-auto overflow-auto">
                <div class="relative container mx-auto px-12 pt-6 pb-24">
                    @yield ('app-notification')
                    @yield ('content')
                </div>
            </main>
@endif

        </div>
    </div>
@endsection

resources/views/layouts/auth.blade.php
@extends ('layouts.boilerplate')

@section ('base')
    <div class="w-screen h-screen">
        <div class="w-full h-full flex items-center md:items-start justify-between overflow-hidden">
            <div class="w-full h-full md:max-w-lg mx-auto mx-0 overflow-auto">
                <div class="p-12 pt-24">
                    <div class="-mt-12">
                        <a
                            href="/"
                            class="inline-block mb-16"
                        >
                            <img
                                src="/images/logo.svg"
                                alt="Logo"
                                class="h-12 w-auto"
                            />
                        </a>
                    </div>
                    @yield ('content')
                </div>
            </div>
            <div class="hidden md:block relative h-full flex-1">
                <div class="absolute w-full h-full bg-blue-500 opacity-50"></div>
                <img
                    src="https://images.unsplash.com/photo-1522071820081-009f0129c71c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80"
                    alt="People working on a project"
                    class="w-full h-full object-cover"
                >
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/boilerplate.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
<div id="app" class="font-sans bg-gray-100">
    @yield ('base')
</div>
</body>
</html>

resources/views/layouts/settings.blade.php
@extends ('layouts.app')


@section('extra_content_h1')
    <div class="flex items-center justify-between py-2 pl-6 border-b border-gray-idk mb-2">
        <h1 class="text-4xl text-gray-900 font-bold">Settings</h1>
    </div>
@endsection

@section('extra_content_aside')

<div class="second-aside ">

    <p>General</p>

    <ul>

        <li class="">
            <a href="{{ route('settings.profile') }}" class="{{ Route::currentRouteName() == 'settings.profile' ? 'active' : null }}">Profile</a>
        </li>

        <li class="">
            <a href="{{ route('settings.profile') }}">Account</a>
        </li>

        <li class="">
            <a href="{{ route('settings.profile') }}">Notifications</a>
        </li>

        <li class="">
            <a href="{{ route('settings.password') }}" class="{{ Route::currentRouteName() == 'settings.password' ? 'active' : null }}">Password</a>
        </li>

        <li class="">
            <a href="{{ route('settings.profile') }}" class="red">Deactivate</a>
        </li>

    </ul>

</div>

@endsection