routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::prefix('/auth')->group(function () {
    Auth::routes();
});

Route::get('/@{user}', 'ProfileController@show')->name('profile.show');
Route::get('/@{user}/edit', 'ProfileController@edit')->name('profile.edit');

Route::get('/notifications', 'NotificationController@index')->name('notifications');

Route::prefix('/conversations')->namespace('Conversations')->name('conversation.')->middleware('auth')->group(function () {
    Route::get('/', 'ConversationController@index')->name('index');
    Route::get('/list', 'ConversationController@get_conversations')->name('list');
    Route::get('/new', 'ConversationController@new')->name('new');
    Route::get('/{user}/messages', 'ConversationController@messages')->name('messages');
    Route::post('/{user}/send', 'ConversationController@send')->name('send');
});

Route::prefix('/settings')
        ->name('settings.')
        ->middleware(['auth'])
        ->namespace('Settings')
        ->group(function () {

    Route::get('/', function () {
        return redirect()->route('settings.profile');
    });

    Route::get('/profile', 'ProfileSettingsController@edit')->name('profile'); // profile picture, biography, website ...
    Route::patch('/profile', 'ProfileSettingsController@update')->name('profile.update'); // save

    Route::get('/password', 'PasswordSettingsController@edit')->name('password');
    Route::patch('/password', 'PasswordSettingsController@update')->name('password.update');

    // Route::get('/account', 'SettingsController@index')->name('profile'); // username, deactivate account
    // Route::get('/privacy', 'SettingsController@privacy')->name('settings.privacy');
    // Route::get('/notifications', 'SettingsController@notifications')->name('settings.notifications');
    // Route::resource('/deactivate', 'SettingsController')->only(['index', 'delete']);

});

Route::prefix('/discussions')->namespace('Discussions')->group(function () {
    Route::get('/{category?}', 'DiscussionController@index')->name('discussion.index'); // category is optional
    Route::get('/{category}/create', 'DiscussionController@create')->name('discussion.create');
    Route::post('/{category}', 'DiscussionController@store')->name('discussion.store');
    Route::get('/{category}/{discussion}', 'DiscussionController@show')->name('discussion.show');
    Route::get('/{category}/{discussion}/edit', 'DiscussionController@edit')->name('discussion.edit');
    Route::patch('/{category}/{discussion}', 'DiscussionController@update')->name('discussion.update');
    Route::delete('/{category}/{discussion}', 'DiscussionController@destroy')->name('discussion.delete');

    Route::post('/{category}/{discussion}/likes', 'DiscussionLikeController@store')->name('discussion.like.store');
    Route::delete('/{category}/{discussion}/likes', 'DiscussionLikeController@destroy')->name('discussion.like.destroy');

    Route::post('/{category}/{discussion}/lock', 'DiscussionLockController@store')->name('discussion.lock.store');
    Route::delete('/{category}/{discussion}/lock', 'DiscussionLockController@destroy')->name('discussion.lock.destroy');

    Route::post('/{category}/{discussion}/pin', 'DiscussionPinController@store')->name('discussion.pin.store');
    Route::delete('/{category}/{discussion}/pin', 'DiscussionPinController@destroy')->name('discussion.pin.destroy');

    Route::get('/search', 'DiscussionSearchController@search')->name('discussion.search');

    Route::prefix('/{category}/{discussion}/replies')->namespace('Replies')->group(function () {
        Route::post('/{reply?}', 'DiscussionReplyController@store')->name('discussion.reply.store');
        Route::post('/{reply}/likes', 'DiscussionReplyLikeController@store')->name('discussion.reply.like.store');
        Route::delete('/{reply}/likes', 'DiscussionReplyLikeController@delete')->name('discussion.reply.like.delete');

        Route::post('/{reply}/best', 'DiscussionBestReplyController@store')->name('discussion.reply.best.store');
    });
});

// admin :
Route::prefix('/admin')->name('admin.')->namespace('Admin')->middleware(['auth', 'role:admin'])->group(function () {

    Route::get('/', 'AdminController@index')->name('index');

    Route::resource('users', 'UserController'); // names van 'resource' routes worden automatisch gegenereerd

    Route::get('/invite-users', 'UserInviteController@form')->name('invite-users');
    Route::post('/invite-users', 'UserInviteController@send_invites')->name('invite-users.send');

    Route::resource('projects', 'ProjectController');

    Route::resource('categories', 'CategoryController');

});

app/Category.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use Sluggable;

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function path()
    {
        return route('discussion.index', $this);
    }

    public function discussions()
    {
        return $this->hasMany('App\Discussion');
    }

    public function latestDiscussion()
    {
        return $this->hasOne(Discussion::class)->latest();
    }

    public function replies()
    {
        return $this->hasManyThrough(Reply::class, Discussion::class);
    }

    public function parent()
    {
        return $this->belongsTo('App\Category', 'parent_id', 'id');
    }

    public function children()
    {
        return $this->hasMany('App\Category', 'parent_id')->with('children');
    }

    public function breadcrumbs()
    {
        $breadcrumbs = [];

        $breadcrumbs = array_merge($breadcrumbs, [
            $this->title => [
                'title' => $this->title,
                'url' => $this->path(),
            ],
        ]);

        $parentCategory = $this->parent;
        while ($parentCategory != null) {
            $breadcrumbs = array_merge($breadcrumbs, [
                $parentCategory->title => [
                    'title' => $parentCategory->title,
                    'url' => $parentCategory->path(),
                ],
            ]);

            $parentCategory = $parentCategory->parent;
        }

        $breadcrumbs = array_reverse($breadcrumbs);

        return $breadcrumbs;
    }

    /**
     * @inheritDoc
     */
    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title',
            ],
        ];
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'id'=>'required',
            'slug'=>'required',
            'title'=>'required',
            'order'=>'required',
            'description'=>'required',
            'img_url'=>'required',
            'is_closed'=>'required'
        ]);

        $cateogry = new Category([
            'id' => $request->get('id'),
            'slug' => $request->get('slug'),
            'title' => $request->get('title'),
            'order' => $request->get('order'),
            'description' => $request->get('description'),
            'img_url' => $request->get('img_url'),
            'is_closed' => $request->get('is_closed')
        ]);
        $category->save();
        return redirect(route('admin.categories.index'))->with('success', 'Category saved.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        //$category = Category::find($id);
        return view('admin.categories.edit', compact('categories', 'category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'slug'=>'required',
            'title'=>'required',
            'order'=>'required',
            'body'=>'required',
            'image_url'=>'required',
            'is_closed'=>'required'
        ]);

        $category->slug = $request->get('slug');
        $category->title = $request->get('title');
        $category->order = $request->get('order');
        $category->body = $request->get('body');
        $category->image_url = $request->get('image_url');
        $category->is_closed = $request->get('is_closed');
        $category->save();

        return redirect(route('admin.categories.index'))->with(['status' => 'Category updated.', 'type' => 'success']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect(route('admin.categories.index'))->with(['status' => 'Category deleted.', 'type' => 'success']);
    }
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-sm-8 offset-sm-2">
        <h1 class="display-3 text-xl mb-1">Update a category</h1>

        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <br />
        @endif
        <form method="post" action="{{ route('admin.categories.update', $category) }}">
            @method('PATCH')
            @csrf
            <div class="form-group">
                <label for="first_name" class="w-32 inline-block">parentid:</label>
                <input type="text" class="form-control mb-2 pl-1 border" name="parent_id" value={{ $category->parent_id }} >
            </div>
            <div class="form-group">
                <label for="first_name" class="w-32 inline-block">Slug:</label>
                <input type="text" class="form-control mb-2 pl-1 border" name="slug" value={{ $category->slug }} >
            </div>
            <div class="form-group">
                <label for="email" class="w-32 inline-block">Title:</label>
                <input type="text" class="form-control mb-2 pl-1 border" name="title" value={{ $category->title }} >
            </div>
            <div class="form-group">
                <label for="email" class="w-32 inline-block">Order:</label>
                <input type="text" class="form-control mb-2 pl-1 border" name="order" value={{ $category->order }} >
            </div>
            <div class="form-group">
                <label for="city" class="w-32 inline-block">Description:</label>
                <textarea class="form-control mb-2 pl-1 border max-w-xs w-full" name="body">{{ $category->body }}</textarea>
            </div>
            <div class="form-group">
                <label for="city" class="w-32 inline-block">Image URL:</label>
                <input type="text" class="form-control mb-2 pl-1 border" name="image_url" value={{ $category->image_url }} >
            </div>
            <div class="form-group">
                <label for="city" class="w-32 inline-block">Closed:</label>
                <input type="text" class="form-control mb-2 pl-1 border" name="is_closed" value={{ $category->is_closed }} >
            </div>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.index')

@section('tabmenu')

<div class="row py-4 px-4">
<div class="col-sm-12">
  <table class="table-auto">
    <thead>
        <tr>
          <th class="px-4 py-2">ID</th>
          <th class="px-4 py-2">ParentID</th>
          <th class="px-4 py-2">Slug</th>
          <th class="px-4 py-2">Title</th>
          <th class="px-4 py-2">Order</th>
          <th class="px-4 py-2">Description</th>
          <th class="px-4 py-2">Image</th>
          <th class="px-4 py-2">Closed</th>
          <th class="px-4 py-2" colspan="2">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach($categories as $category)
        <tr>
            <td class="border px-4 py-2">{{$category->id}}</td>
            <td class="border px-4 py-2">{{$category->parent_id}}</td>
            <td class="border px-4 py-2">{{$category->slug}}</td>
            <td class="border px-4 py-2">{{$category->title}}</td>
            <td class="border px-4 py-2">{{$category->order}}</td>
            <td class="border px-4 py-2">{{$category->body}}</td>
            <td class="border px-4 py-2"><img src="{{$category->image_url}}" /></td>
            <td class="border px-4 py-2">{{$category->is_closed}}</td>
            <td class="border px-4 py-2">
                <a href="{{ route('admin.categories.edit', $category)}}">
                <button class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M15.2322 5.23223L18.7677 8.76777M16.7322 3.73223C17.7085 2.75592 19.2914 2.75592 20.2677 3.73223C21.244 4.70854 21.244 6.29146 20.2677 7.26777L6.5 21.0355H3V17.4644L16.7322 3.73223Z" stroke="#4A5568" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </button>
                </a>
            </td>
            <td class="border px-4 py-2">
                <form action="{{ route('admin.categories.destroy', $category)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow" type="submit">
                  <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M19 7L18.1327 19.1425C18.0579 20.1891 17.187 21 16.1378 21H7.86224C6.81296 21 5.94208 20.1891 5.86732 19.1425L5 7M10 11V17M14 11V17M15 7V4C15 3.44772 14.5523 3 14 3H10C9.44772 3 9 3.44772 9 4V7M4 7H20" stroke="#4A5568" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                  </svg></button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
</div>
</div>

@endsection