routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::prefix('/auth')->group(function () {
    Auth::routes();
});

Route::get('/@{user}', 'ProfileController@show')->name('profile.show');
Route::get('/@{user}/edit', 'ProfileController@edit')->name('profile.edit');

Route::get('/notifications', 'NotificationController@index')->name('notifications');

Route::prefix('/conversations')->namespace('Conversations')->name('conversation.')->middleware('auth')->group(function () {
    Route::get('/', 'ConversationController@index')->name('index');
    Route::get('/list', 'ConversationController@get_conversations')->name('list');
    Route::get('/new', 'ConversationController@new')->name('new');
    Route::get('/{user}/messages', 'ConversationController@messages')->name('messages');
    Route::post('/{user}/send', 'ConversationController@send')->name('send');
});

Route::prefix('/settings')
        ->name('settings.')
        ->middleware(['auth'])
        ->namespace('Settings')
        ->group(function () {

    Route::get('/', function () {
        return redirect()->route('settings.profile');
    });

    Route::get('/profile', 'ProfileSettingsController@edit')->name('profile'); // profile picture, biography, website ...
    Route::patch('/profile', 'ProfileSettingsController@update')->name('profile.update'); // save

    Route::get('/password', 'PasswordSettingsController@edit')->name('password');
    Route::patch('/password', 'PasswordSettingsController@update')->name('password.update');

    // Route::get('/account', 'SettingsController@index')->name('profile'); // username, deactivate account
    // Route::get('/privacy', 'SettingsController@privacy')->name('settings.privacy');
    // Route::get('/notifications', 'SettingsController@notifications')->name('settings.notifications');
    // Route::resource('/deactivate', 'SettingsController')->only(['index', 'delete']);

});

Route::prefix('/discussions')->namespace('Discussions')->group(function () {
    Route::get('/{category?}', 'DiscussionController@index')->name('discussion.index'); // category is optional
    Route::get('/{category}/create', 'DiscussionController@create')->name('discussion.create');
    Route::post('/{category}', 'DiscussionController@store')->name('discussion.store');
    Route::get('/{category}/{discussion}', 'DiscussionController@show')->name('discussion.show');
    Route::get('/{category}/{discussion}/edit', 'DiscussionController@edit')->name('discussion.edit');
    Route::patch('/{category}/{discussion}', 'DiscussionController@update')->name('discussion.update');
    Route::delete('/{category}/{discussion}', 'DiscussionController@destroy')->name('discussion.delete');

    Route::post('/{category}/{discussion}/likes', 'DiscussionLikeController@store')->name('discussion.like.store');
    Route::delete('/{category}/{discussion}/likes', 'DiscussionLikeController@destroy')->name('discussion.like.destroy');

    Route::post('/{category}/{discussion}/lock', 'DiscussionLockController@store')->name('discussion.lock.store');
    Route::delete('/{category}/{discussion}/lock', 'DiscussionLockController@destroy')->name('discussion.lock.destroy');

    Route::post('/{category}/{discussion}/pin', 'DiscussionPinController@store')->name('discussion.pin.store');
    Route::delete('/{category}/{discussion}/pin', 'DiscussionPinController@destroy')->name('discussion.pin.destroy');

    Route::get('/search', 'DiscussionSearchController@search')->name('discussion.search');

    Route::prefix('/{category}/{discussion}/replies')->namespace('Replies')->group(function () {
        Route::post('/{reply?}', 'DiscussionReplyController@store')->name('discussion.reply.store');
        Route::post('/{reply}/likes', 'DiscussionReplyLikeController@store')->name('discussion.reply.like.store');
        Route::delete('/{reply}/likes', 'DiscussionReplyLikeController@delete')->name('discussion.reply.like.delete');

        Route::post('/{reply}/best', 'DiscussionBestReplyController@store')->name('discussion.reply.best.store');
    });
});

// admin :
Route::prefix('/admin')->name('admin.')->namespace('Admin')->middleware(['auth', 'role:admin'])->group(function () {

    Route::get('/', 'AdminController@index')->name('index');

    Route::resource('users', 'UserController'); // names van 'resource' routes worden automatisch gegenereerd

    Route::get('/invite-users', 'UserInviteController@form')->name('invite-users');
    Route::post('/invite-users', 'UserInviteController@send_invites')->name('invite-users.send');

    Route::resource('projects', 'ProjectController');

    Route::resource('categories', 'CategoryController');

});

app/Http/Controllers/Settings/PasswordSettingsController.php
<?php

namespace App\Http\Controllers\Settings;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class PasswordSettingsController extends Controller
{

    /**
     * Show a profile.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function edit()
    {
        return view('settings.password');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function update(Request $request)
    {
        $user = Auth::user();

        $valid_data = Validator::make($request->all(), [
            'old_password' => ['required', 'password:web'],
            'new_password' => ['required', 'string', 'min:8', 'confirmed']
        ])->validate();

        if ($valid_data['old_password'] != $valid_data['new_password'])
        {
            $user->password = Hash::make($valid_data['new_password']);
            $user->save();

            $status = 'Successfully changed your password';
            $type = 'success';
        }
        else
        {
            $status = 'Your password has not been modified';
            $type = 'info';
        }

        return redirect()->back()->with([
            'status' => $status,
            'type' => $type,
            'duration' => 10,
        ]);

    }

}

app/Http/Controllers/Settings/ProfileSettingsController.php
<?php

namespace App\Http\Controllers\Settings;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;

class ProfileSettingsController extends Controller
{

    /**
     * Show a profile.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function edit()
    {
        return view('settings.profile');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function update(Request $request)
    {
        $user = Auth::user();

        $valid_data = Validator::make($request->all(), [
            'username' => ['required', 'string', 'max:255', 'unique:users,username,'.$user->id.',id', 'alpha_dash']
        ])->validate();

        $user->fill($valid_data);

        if ($user->isDirty())
            $status = 'Successfully saved';
        else
            $status = 'No changes were made';

        $user->save();

        return redirect()->back()->with([
            'status' => $status,
            'type' => 'success',
            'duration' => 10,
        ]);

    }

}

resources/views/settings/password.blade.php
@extends('layouts.settings')

@section('content')
    <div class="flex items-center justify-between pb-3  mt-4 mb-2">
        <h2 class="text-3xl text-gray-900 font-bold">Edit your password</h1>
    </div>
    <div class="flex flex-col">
        <div class="w-full md:w-1/2">
            <div class="bg-white p-8 rounded-md shadow-lg">

				<!-- default form -->
				<form class="w-full max-w-lg md:max-w-full" action="{{ route('settings.password.update') }}" method="POST">
                    @csrf
                    <input name="_method" type="hidden" value="PATCH">

					<div class="mb-6 px-3 md:flex">
						<label class="block tracking-wide text-gray-700 text-sm font-medium mb-2 md:w-2/5 md:h-full md:text-right md:mr-6 md:py-1" for="field-old-password">
							Old password
						</label>
                        <div class="md:w-3/5">
						    <input name="old_password" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-300 rounded py-1 px-3 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 md:text-sm" id="field-old-password" type="password" placeholder="**********">
                            @error ('old_password')
                                <p class="text-red-600 text-xs italic">{{ $message }}</p>
                            @enderror
					    </div>
					</div>

                    <div class="border-b border-gray-300 mb-6"></div>

					<div class="mb-6 px-3 md:flex">
						<label class="block tracking-wide text-gray-700 text-sm font-medium mb-2 md:w-2/5 md:h-full md:text-right md:mr-6 md:py-1" for="field-new-password">
							New password
						</label>
                        <div class="md:w-3/5">
						    <input name="new_password" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-300 rounded py-1 px-3 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 md:text-sm" id="field-new-password" type="password" placeholder="**********">
                            @error ('new_password')
                                <p class="text-red-600 text-xs italic">{{ $message }}</p>
                            @enderror
					    </div>
					</div>
					<div class="mb-6 px-3 md:flex">
						<label class="block tracking-wide text-gray-700 text-sm font-medium mb-2 md:w-2/5 md:h-full md:text-right md:mr-6 md:py-1" for="field-new-password-confirm">
							Confirm new password
						</label>
                        <div class="md:w-3/5">
						    <input name="new_password_confirmation" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-300 rounded py-1 px-3 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 md:text-sm" id="field-new-password-confirm" type="password" placeholder="**********">
					    </div>
					</div>

                    <div class="mb-2 px-3 md:flex">
                        <div class="md:w-1/4 md:mr-6"></div>
                        <div class="md:w-3/4">
                            <button type="submit" class="btn btn-blue">Update</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>

    </div>
@endsection

resources/views/settings/profile.blade.php
@extends('layouts.settings')

@section('content')
    <div class="flex items-center justify-between pb-3  mt-4 mb-2">
        <h2 class="text-3xl text-gray-900 font-bold">Edit your profile</h1>
    </div>
    <div class="flex flex-col">
        <div class="w-full md:w-1/2">
            <div class="bg-white p-8 rounded-md shadow-lg">

				<!-- default form -->
				<form class="w-full max-w-lg md:max-w-full" action="{{ route('settings.profile.update') }}" method="POST">
                    @csrf
                    <input name="_method" type="hidden" value="PATCH">

					<div class="mb-6 px-3 md:flex">
						<label class="block tracking-wide text-gray-700 text-sm font-medium mb-2 md:w-1/4 md:h-full md:text-right md:mr-6 md:py-1" for="grid-username">
							Username
						</label>
                        <div class="md:w-3/4">
						    <input name="username" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-300 rounded py-1 px-3 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 md:text-sm" id="grid-username" type="text" value="{{ Auth::user()->username }}">
                            @error ('username')
                                <p class="text-red-600 text-xs italic">{{ $message }}</p>
                            @enderror
					    </div>
					</div>

					<div class="mb-6 px-3 md:flex">
						<label class="block tracking-wide text-gray-700 text-sm font-medium mb-2 md:w-1/4 md:h-full md:text-right md:mr-6 md:py-1">
							Email
						</label>
                        <div class="md:w-3/4">
                            <input name="asd" class="cursor-not-allowed appearance-none block w-full bg-gray-300 text-gray-700 border border-gray-400 rounded py-1 px-3 mb-3 leading-tight md:text-sm" type="text" value="{{ Auth::user()->email }}" disabled>
						    <p class="text-gray-600 text-xs italic">You can't change your email because you were invited</p>
                        </div>
					</div>

					<div class="mb-6 px-3 md:flex">
						<label class="block tracking-wide text-gray-700 text-sm font-medium mb-2 md:w-1/4 md:h-full md:text-right md:mr-6 md:py-1" for="grid-first-name">
							Gitea-URL
						</label>
                        <div class="md:w-3/4">
                            <input class="cursor-not-allowed appearance-none block w-full bg-gray-300 text-gray-700 border border-gray-400 rounded py-1 px-3 mb-3 leading-tight  md:text-sm" type="text" value="{{ Auth::user()->get_git_url() }}" disabled>
						    <p class="text-gray-600 text-xs italic">You can't change your gitea-url because it was created alongside your account</p>
                        </div>
					</div>

                    {{--
					<div class="mb-6 px-3 md:flex">
						<label class="block tracking-wide text-gray-700 text-sm font-bold mb-2 md:w-1/4 md:h-full md:text-right md:mr-6 md:py-1"  for="grid-homepage">
							Homepage
						</label>
                        <div class="md:w-3/4">
                            <input name="username" class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-300 rounded py-1 px-3 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 md:text-sm" type="text" id="grid-homepage" value="{{ Auth::user()->homepage }}">
                        </div>
					</div>

					<div class="mb-6 px-3 md:flex">
						<label class="block tracking-wide text-gray-700 text-sm font-bold mb-2 md:w-1/4 md:h-full md:text-right md:mr-6 md:py-1" for="grid-biography">
							Biography
						</label>
                        <div class="md:w-3/4">
                            <textarea name="biography" class="appearance-none block min-h-10 w-full bg-gray-200 text-gray-700 border border-gray-300 rounded py-1 px-3 mb-3 leading-tight focus:outline-none focus:bg-white focus:border-gray-500 md:text-sm" id="grid-biography">{{ Auth::user()->biography }}</textarea>
                        </div>
					</div>
                    --}}

                    <div class="mb-2 px-3 md:flex">
                        <div class="md:w-1/4 md:mr-6"></div>
                        <div class="md:w-3/4 ">
                            <button type="submit" class="btn btn-blue">Update</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>

    </div>
@endsection